### ISSUE TITLE
Prompt is printed twice when play ends

### ISSUE THREAD

**Issue by juhana** [vorple/vorple#20]

**Comment by hlabrand** [comment]
Looking at the library, this also happens when asking yes or no to the player and something else is typed.

**Comment by hlabrand** [comment]
The problem is that some prompts are hard-coded in the library (routines AfterGameOver and YesOrNo in I6). I don't know if they should be, but they are (maybe we should ask if this is really desired?). Most of the time they are displayed through L__M(##Prompt) (in I6) or PrintPrompt (in I7), except at those two places, where those routines arent called and the prompt is hardcoded instead.

Vorple, if I understand right, prints the prompt whenever reading a command. When the library hardcodes a prompt then reads a command, there's your duplicate.

Proposed fix: Vorple should print the prompt only if a variable is equal to 1, in which case it prints the vorple prompt and sets that variable to 0. In L__M(##Prompt) / PrintPrompt, we put a JS call that sets that variable to 1. This way Vorple only prints the prompt whenever there would have been a call to L__M(##Prompt)/PrintPrompt (i.e. everywhere but the two routines where the prompt is hardcoded).
