### ISSUE TITLE
Toastr doesn't show accented characters correctly

### ISSUE THREAD

**Issue by juhana** [vorple/vorple#22]

**Comment by Natrium729** [comment]
Not only Toastr. All special characters used in JavaScript do not display correctly, it seems. For example:

```
When play begins:
	execute Javascript command "'éèçàºƒÈ∂'";
	say "[text returned by the JavaScript command][line break]";
	say "éèçàºƒÈ∂";
```

The first line doesn't show the correct characters.

**Comment by Natrium729** [comment]
Some precisions. Vorple uses external files to execute the JS but, according to the section 23.15. of _Writing with Inform_:

> An Inform file is currently a Unix text file (with 10 as the line division character), encoded as **ASCII Latin-1.** (We would like to use Unicode at some point in the future, but the Glk and Glulx layers are still not fully converted to Unicode.)

I think that the encoding of the external files is the problem.

**Comment by Natrium729** [comment]
More precisions:

It is possible to display unicode characters in JS with `\uXXXX` where `XXXX` is the code of the character.

Unfortunately, since the Vorple extensions escapes the texts in its phrases, the backslash is escaped and the unicode character is not displayed.

Also, it won't work with values returned by JavaScript that are accessed with Inform, since we retrieve these from the external file. A workaround for the author would be to define some custom replacement for special characters (such as "{e-acute}" for "é") and replace them with Inform before displaying the text.

**Comment by juhana** [comment]
First of all, thanks for all the bug reports! I'll try to go through them as soon as I get the time.

It shouldn't be hard to make the interpreter write Unicode files (unless it requires support from Inform, of which I'm not sure) but first I'll have to study more closely how Glulx/Glk handles Unicode in general. In the meanwhile I can make the "escaped (text)" phrases turn Unicode characters into the `\uXXXX` format.
