### ISSUE TITLE
Modal windows and small font

### ISSUE THREAD

**Issue by hlabrand** [vorple/vorple#26]
When writing in small font in a modal window, the line spacing is way too large and it doesn't look good. This is because vorple.min.css defines line-height:1.5em in vex-content. This value should be changed to something relative to the font size (like 120%, which seems to work well, although 110% is also good).

**Comment by juhana** [comment]
The problem with this is that because the small font style is applied to separate inline spans instead of a block-level container, the percentages would also apply to the base size, so there isn't a very good direct solution when the entire contents is only small fonts coming from Vorple styles in Inform.

Workaround is to create a block level element, apply the small font class or style to it, put it inside the modal and print the text in the element.
