### ISSUE TITLE
Ideas for single file secure Vorple blorbs

### ISSUE THREAD

**Issue by curiousdannii** [vorple/vorple#30]
I just read [Graham's recent presentation](http://www.emshort.com/ifmu/inform.html), and it got me thinking again about how I might design an ecosystem that would allow for single file secure Vorple blorbs. This is all very rough, but I think quite feasible.

1. Implement JS streams and events, so that communication doesn't have to happen through the file API.
2. Load an ES module from a standard blorb chunk. The module would export one function, which would accept an options object, one of which is a function to call to send a JSON event to the VM. It would return a function on which it should be called when there is JSON to be received from the VM.
3. Also load a CSS file from a standard blorb chunk.
4. Have a blorb chunk which maps between blorb resource numbers and text names, and expose them to the ES module, maybe as Blobs.

This is the sort of direction I want to move my own projects in. It's a generic JS-VM system, not specific to Vorple. It would be possible to overhaul Vorple (again) to work entirely within such a sandbox, or to have a combined type system where the Vorple files are loaded separately, and the blorb JS chunk is just for user code.

I've also been thinking about how to make this secure, and I think if it's wrapped up like this in a blorb, then it will be very possible to make such a game be securely loaded and sandboxed in the browser, in Lectrote, and in mobile interpreters.

As I said, this is how I am thinking of eventually moving my projects. It may not suit how you want to develop Vorple, which is perfectly fine! I wanted to write something down while the thoughts were clear in my head.

**Comment by juhana** [comment]
Due to practical reasons, instead of the interpreter-storyfile model I've settled on a design where the two are inseparable which I think goes against your plan – but I do like the idea of blorbing all resource files together, and I wouldn't mind a standard-compliant way to evaluate JavaScript in the future. I don't see why there couldn't be two options for authors, the current system for those who need no restrictions whatsoever and the new system for those who are ok with the sandboxed version.

**Comment by juhana** [comment]
It's unlikely that I'll ever advance the project to this direction, but I'll support anyone wants to work on it (maybe as a fork of the project?)
