### ISSUE TITLE
CSS organization?

### ISSUE THREAD

**Issue by hlabrand** [vorple/vorple#31]
A Vorple project currently has three main CSS files : vorple.css, vorple.min.css and style.css. The first two are big blocks of CSS with no carriage returns, which makes them hard to read; the last one is called first, which means some of its rules get overwritten by others, but since it's in the main folder it feels like it should be the one that the user should want to change.

I'm a beginner in CSS, and my understanding is that you can just pile up rules with the understanding that only the last one will be used. And if I want to change something, I use my browser's tools to figure out what makes this effect and how I can change it (instead of trying to read the css files myself). Still, I can't help but wonder: would it be desirable to clean this up, to make it more readable, or more centralized even, with fewer files?

**Comment by Natrium729** [comment]
I don't know if there are differences between I6 and I7, but here are explanations for what you are asking, with I7.

`vorple.min.css` has a `min` in its name because it's minimised: it has no whitespace nor carriage returns, and comments are stripped. That's on purpose, so that the browser can read it faster. Humans are not supposed to read it.

`vorple.css` isn't supposed to be minimised, so I guess you made a mistake. That's the development version of `vorple.min.css`, that a human can edit. Before making a Vorple release, this file is minimised into `vorple.min.css`.

`style.css` is the CSS for the mini-website generated by Inform 7. It has nothing to do with Vorple, but Inform still includes it on `play.html`.

So I guess the answer to your last question is: no, there isn't the need to clean up CSS files. If you don't like the minimised version, you can still replace it by the non-minimised one, or work on the non-minimised one and minimise it yourself (there are several site that can do this for you).

Also, instead of editing the included Vorple style, you could just write you own CSS file to overwrite CSS rules defined in `vorple.min.css`

Also, the issue #27 might interest you.

**Comment by juhana** [comment]
The main problem is that the I6 HTML page is based on the I7 template, and it includes some unnecessary cruft. I should clean up the I6 template so that it doesn't include anything unnecessary.

Minimizing the CSS doesn't really have any significant benefits and it would make it easier to see what the default rules are, so I'll include the non-minimized version instead in the next release.

**Comment by Natrium729** [comment]
I just noticed that `vorple.min.css` isn't equivalent to `vorple.css`. It also has the CSS from Haven, and for the tooltips, the modals, the notifications and flexbox grid. This makes difficult to modify only Vorple core style.

(Also, I can't find when Vorple uses flexbox grid. Is it safe to remove it?)

**Comment by juhana** [comment]
The flexbox grid is only used in one extension that wasn't even included in the current version. It's safe to remove.

**Comment by juhana** [comment]
Version 3.1 has a simpler CSS file organization and unminified CSS files.
